FROM riga/py-sci:3.9

# install minimal machine learning software stack
RUN pip install --no-cache-dir tensorflow
RUN pip install --no-cache-dir scikit-learn
RUN pip install --no-cache-dir scikit-optimize
