FROM python:3.9

# set the workdir
WORKDIR /root

# minimal software stack
RUN apt-get update; apt-get clean
RUN apt-get install -y nano less htop which; apt-get clean

# install base software
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir --upgrade ipython
RUN pip install --no-cache-dir six
RUN pip install --no-cache-dir flake8
